### ISSUE TITLE
status 127 error: compilation failed for package 'BMR'

### ISSUE THREAD

**Issue by Euanritchie** [kthohr/BMR#11]
Dear All,

I am trying to install the BMR package, and have been following the instructions detailed on this website: http://bayes.squarespace.com/bmr/ .I installed the three packages, and then devtools (after downloading and installing rtools 3.3) and then gave the command  `install_github("kthohr/BMR")`. When I did I got the following output:

    Downloading GitHub repo kthohr/BMR@master
    Installing BMR
    Installing 13 packages: dichromat, doParallel, foreach, ggplot2, gtable, iterators, labeling, munsell, plyr, RColorBrewer, RcppArmadillo, reshape2, scales
    package ‘dichromat’ successfully unpacked and MD5 sums checked
    package ‘doParallel’ successfully unpacked and MD5 sums checked
    package ‘foreach’ successfully unpacked and MD5 sums checked
    package ‘ggplot2’ successfully unpacked and MD5 sums checked
    package ‘gtable’ successfully unpacked and MD5 sums checked
    package ‘iterators’ successfully unpacked and MD5 sums checked
    package ‘labeling’ successfully unpacked and MD5 sums checked
    package ‘munsell’ successfully unpacked and MD5 sums checked
    package ‘plyr’ successfully unpacked and MD5 sums checked
    package ‘RColorBrewer’ successfully unpacked and MD5 sums checked
    package ‘RcppArmadillo’ successfully unpacked and MD5 sums checked
    package ‘reshape2’ successfully unpacked and MD5 sums checked
    package ‘scales’ successfully unpacked and MD5 sums checked
    "C:/PROGRA~1/R/R-32~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
      "C:/Users/EuanRitchie/AppData/Local/Temp/RtmpWCpOq3/devtools31144c7b1c77/kthohr-BMR-81c957c" --library="C:/Users/EuanRitchie/Documents/R/win-library/3.2"  \
      --install-tests 
    
    * installing *source* package 'BMR' ...
    ** libs

    *** arch - i386
    Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-32~1.3/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="BMR.dll" OBJECTS="adfc.o bvarmc.o bvarsc.o bvartvpc.o bvarwc.o cvarc.o dsgec.o dsgevarc.o"' had status     127
    ERROR: compilation failed for package 'BMR'
    * removing 'C:/Users/EuanRitchie/Documents/R/win-library/3.2/BMR'
    Error: Command failed (1)`

I'd be hugely grateful any help. I'm relatively inexperience with R, and software in general, but this tool would be really useful (and I really appreciate it's creation!). I did see that there had been a problem with `makevars` in Linux, but to clarify I am using Windows, and have R version 3.2.3. The other packages I have only just installed so I assume they are the latest. 
Many thanks

**Comment by kthohr** [comment]
'127' errors are (usually) attributable to your Rtools installation. Try
the following commands in R:

library(devtools)

find_rtools(T)

then

has_devel()

Paste the output from these commands here.

**Comment by Euanritchie** [comment]
I'll try that and get back to you asap, many thanks for your response

**Comment by Euanritchie** [comment]
>library(devtools)   
    > find_rtools(T)
    Scanning path...
    Scanning registry...
    Found c:/Rtools for 3.3 
    VERSION.txt
    Rtools version 3.3.0.1959 
    [1] TRUE
    > has_devel()
    "C:/PROGRA~1/R/R-32~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD SHLIB foo.c 

    gcc -m64 -I"C:/PROGRA~1/R/R-32~1.3/include" -DNDEBUG     -I"d:/RCompile/r-    compiling/local/local323/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c foo.c -o foo.o
    gcc -m64 -shared -s -static-libgcc -o foo.dll tmp.def foo.o -Ld:/RCompile/r-compiling/local/local323/lib/x64 -Ld:/RCompile/r-compiling/local/local323/lib -LC:/PROGRA~1/R/R-32~1.3/bin/x64 -lR
    [1] TRUE

These were the results

**Comment by kthohr** [comment]
Did you install Rtools while R was still running?

Try restarting R and installing the package again.

**Comment by Euanritchie** [comment]
Thanks, it works totally fine now. Sorry it was a rather trivial issue!

**Comment by kthohr** [comment]
Glad to hear it works now.
