### ISSUE TITLE
Unable to install BMR

### ISSUE THREAD

**Issue by mosaic92** [kthohr/BMR#12]
When installing, get the following error:

```
* installing *source* package ‘BMR’ ...
* checking LAPACK_LIBS: R-supplied partial LAPACK found
* gensys solver is not available   
.  
.   
.   
ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [BMR.so] Error 1
ERROR: compilation failed for package ‘BMR’
ERROR: Command failed (1)
```

help!

**Comment by kthohr** [comment]
The error is stated rather clearly: you don't have (or the compiler can't
find) gfortran.

**Comment by mosaic92** [comment]
But, in fact, I already have gfortran, the version is 5.2.

**Comment by kthohr** [comment]
R is built with version 4.8. This is a common issue with Macs.

http://thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error/

**Comment by mosaic92** [comment]
thx！
