### ISSUE TITLE
Error: could not find function "gacf"

### ISSUE THREAD

**Issue by HBWu** [kthohr/BMR#13]
Hi. When I run the codes in your BMR manual, I got this error message:

Error: could not find function "gacf"

But ?gacf looks good. I have no idea what is the problem. Attached is the screenshot. Would you please help? Thanks a lot.

![grab](https://cloud.githubusercontent.com/assets/17698777/13698697/b8e8297e-e7b0-11e5-8895-bc68b434b53f.jpg)

**Comment by kthohr** [comment]
Whoops, I forgot to update the Namespace. Try reinstalling the package from GitHub, it should work now.

**Comment by HBWu** [comment]
Thanks. It works now.
