### ISSUE TITLE
Unexpected forecasting results

### ISSUE THREAD

**Issue by thomas-hoppe** [kthohr/BMR#15]
Some questions, which aren't answered by the vignette: What is the difference between:
$MeanForecast and $PointForecast (The MeanForecast is itself a point forecast)? What are the dimensions of the $Forecasts?

**Comment by thomas-hoppe** [comment]
Ok, I inspected the code further and found that with shocks=T a larger number of samples for the shocks is drawn randomly. However, by the law of large numbers, I wouldn't expect that the MeanForecasts above vary so strongly. Is it an issue, or do I miss something?

**Comment by kthohr** [comment]
PointForecast corresponds to the mid value in the 'percentiles' input; e.g., if you pass, say, c(0.05,0.50,0.95), forecast will be the 50-th percentile of the forecast distribution at each point.

The dimension of Forecasts is: (forecast periods) x (number of equations) x (number of parameter draws).

**Comment by thomas-hoppe** [comment]
Thanks, so actually $PointForecast should be called more precisely $MedianForecast, right?

**Comment by kthohr** [comment]
No. 'Point' refers to the point in the distribution that the user is interested in. If you pass, say, percentiles = (0.05, 0.4, 0.95), then the function will return the 40th percentile.
