### ISSUE TITLE
Run-time for BVARW

### ISSUE THREAD

**Issue by as4456** [kthohr/BMR#16]
Hi Keith,

I am currently using the BVARW function for a study. There is a significant running time when I am estimating on a model with 204 obs, 6 lags and 5 vars. I am currently running this on a 4 core machine.

To compare the performance, I used the BVARW example provided in the vignette with one core . i.e
testbvarw <- BVARW(USMacroData[,2:4],cores=1,c(0.9,0.95,0.95),p=4,constant=T,irf.periods=20,
keep=10000,burnin=5000,XiBeta=4,XiSigma=1,gamma=NULL)

It takes 6 min to run. The run-time is significantly different from the one you have shown in the book which is roughly around 22 sec. 

Could you tell me what could be the plausible cause for this difference.

Thanks

**Comment by kthohr** [comment]
Two reasons.

1) You have 150 coefficients, versus the 36 in my example.

2) The BVARW code in the main branch is inefficient; the 'bvarm-ext-vars’ branch contains a faster implementation but I haven’t, yet, found the time to finish all the changes.

And working on a ‘4 core machine’ is only useful if you’re using a multithreaded BLAS/Lapack library with R.

Keith

**Comment by as4456** [comment]
Ok, I understand the coefficient space is large in my case but regarding the testbvarw example you provided in the vignette, the runtime should ideally be around the same. It takes 6 minute for that example or did you use bvarm-ext-var implementation for that too.

**Comment by kthohr** [comment]
That runtime is based on the implementation in the main branch.

**Comment by OLUJID** [comment]
Pls help me. I installed BMR, BVARS, BVARSV, bvartools. Each time i run bvarw or bvarinw code, I have error "function bvarinw or bvarw is not found". What can I do?
