### ISSUE TITLE
Estimated Covariance matrix

### ISSUE THREAD

**Issue by as4456** [kthohr/BMR#17]
Hi,
I am estimating a BVARM model using 4 vars and 9 lags.
I need to determine the estimated covariance matrix. For the above e.g, its dimension should be 36*36.
Currently the model only has the prior covariance matrix (dimension: 144*144) .
Is there a way to obtain the estimated covariance matrix.

Thanks

**Comment by kthohr** [comment]
Somehow I missed the e-mail about this issue...

144 x 144 sounds correct. There are 36 coefficients in each 'equation' and 4 variables.
