### ISSUE TITLE
Unable to install BMR in Ubuntu 17.04, Windows 7 and Fedora properly

### ISSUE THREAD

**Issue by Krishnendu1986** [kthohr/BMR#19]
Warning: S3 methods ‘modecheck.Rcpp_dsge_gensys’, ‘modecheck.Rcpp_dsgevar_gensys’ were declared in NAMESPACE but not found

**Comment by Krishnendu1986** [comment]
The same problem exists in other OS, such as: Windows 7 & Fedora

S3 methods ‘modecheck.Rcpp_dsge_gensys’, ‘modecheck.Rcpp_dsgevar_gensys’ were declared in NAMESPACE but not found

**Comment by Krishnendu1986** [comment]
While installing BMR (Bayesian Macroeconometrics in R) package in any of the above-mentioned Operating systems I am getting the following Warning/Error message:

Warning: S3 methods ‘modecheck.Rcpp_dsge_gensys’, ‘modecheck.Rcpp_dsgevar_gensys’ were declared in NAMESPACE but not found

Kindly help.

**Comment by kthohr** [comment]
You received that warning message because those methods were missing. They are missing no longer.
