### ISSUE TITLE
problem with function "uhlig", and some of the other functions

### ISSUE THREAD

**Issue by Krishnendu1986** [kthohr/BMR#20]
whenever trying to solve a DSGE model using Uhlig's method... getting the following Error:

> dsgetest <- uhlig(A,B,C,D,F,G,H,J,K,L,M,N)
Error in uhlig(A, B, C, D, F, G, H, J, K, L, M, N) : 
  could not find function "uhlig"

**Comment by kthohr** [comment]
Those examples are from the previous version. Install from the legacy branch if you want to run them.
