### ISSUE TITLE
dsge var parameter estimates and standard errors (se) at the posterior mode:

### ISSUE THREAD

**Issue by hudsonchaves** [kthohr/BMR#23]
Hi, 

Can you say how to obtain parameter estimates and standard errors at the posterior mode for dsge var? I used the package in your old version and now i need to actualize my estimates.

**Comment by kthohr** [comment]
That would be the estim_mode member function. For an example, see: tests/dsge/gensys/nkm_dsgevar.R 

The function will return mode_vals and vcov_mat. To obtain standard errors, use
```
mode_res <- obj$estim_mode(x,TRUE)
ses <- sqrt(diag(mode_res$vcov_mat))
```

**Comment by hudsonchaves** [comment]
Hi, thanks for your response. I'll test.
