### ISSUE TITLE
issue while installing the package

### ISSUE THREAD

**Issue by piotr000** [kthohr/BMR#24]
Hi,
Could you help me out as I can not install bmr package? I get this warning:
C:/Program Files/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATSLIB_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Users/hp/Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/hp/Documents/R/win-library/3.4/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c bmlib/src/optim/unconstrained/de.cpp -o bmlib/src/optim/unconstrained/de.o
C:/Program: not found
make: *** [bmlib/src/optim/unconstrained/de.o] Error 127
followed by: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-34~1.3/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-34~1.3/share/make/winshlib.mk" SHLIB="BMR.dll" WIN=64 TCLBIN=64 OBJECTS=""' has received status 2.
What should I do in order to fix it?

**Comment by kthohr** [comment]
Looks like an Rtools issue---you have a space in your g++ filepath that is not enclosed in quotation marks (C:/Program Files/[...]), hence the broken link. 

From my experience, it's better to install Rtools (and R) to plain C:\ rather than 'Program Files'. This is covered by the R-admin documentation; see the [Windows Toolset](https://cran.r-project.org/doc/manuals/R-admin.html#The-Windows-toolset) appendix.

**Comment by piotr000** [comment]
Many thanks, Keith. Problem solved.


Best,


Piotr


________________________________
Od: kthohr <notifications@github.com>
Wysłane: 4 lutego 2018 12:46
Do: kthohr/BMR
DW: piotr000; Author
Temat: Re: [kthohr/BMR] issue while installing the package (#24)


Looks like an Rtools issue---you have a space in your g++ filepath that is not enclosed in quotation marks (C:/Program Files/[...]), hence the broken link.

From my experience, it's better to install Rtools (and R) to plain C:\ rather than 'Program Files'. This is covered by the R-admin documentation; see the Windows Toolset<https://cran.r-project.org/doc/manuals/R-admin.html#The-Windows-toolset> appendix.
