### ISSUE TITLE
could not find function "BVARM"

### ISSUE THREAD

**Issue by sierrajulie** [kthohr/BMR#25]
Hi, I am trying to replicate "6.1 Monte Carlo Study" in the BMR documentation. However, I do get an error: could not find function "BVARM". 

I'm sure that I have properly installed the required packages. Could you please help?

6.1 Monte Carlo Study Example
data(BMRMCData)
testbvarm <- BVARM(bvarMCdata,c(0.5,0.5),p=2,constant=TRUE,irf.periods=20,
keep=10000,burnin=5000,VType=1,
HP1=0.5,HP2=0.5,HP3=10)

**Comment by kthohr** [comment]
The vignette is based on a previous iteration of the package. See [here](http://www.kthohr.com/bmr_docs_vars_bvarm.html) for updated documentation.
 
The following code should work.
```R
data(BMRMCData)

bvar_obj <- new(bvarm) 

bvar_obj$build(bvarMCdata,TRUE,2)
bvar_obj$prior(c(0.5,0.5),1,1,0.5,0.5,100.0,1.0)
bvar_obj$gibbs(10000)

IRF(bvar_obj,20,save=FALSE)
```
