### ISSUE TITLE
IRF

### ISSUE THREAD

**Issue by khmahmood** [kthohr/BMR#27]
I hope that I do not bother you. Thank you so much for this wonderful package. I really want to use the IRF function, could you please explain how can I compute it or mention  to a good a reference? also what does (horizon) mean in the IRF plot?

Thanks in advance.

**Comment by kthohr** [comment]
There are several options available for the IRF functions. You can find the definitions here: https://github.com/kthohr/BMR/blob/master/R/IRF.R. 

For example, for the `bvarm` model:
```R
IRF.Rcpp_bvarm <- function(obj,periods=10,cumulative=FALSE,cumul_inds=NULL,var_names=NULL,percentiles=c(.05,.50,.95),
                           which_shock=NULL,which_response=NULL,shocks_row_order=TRUE,save=FALSE,save_format=c("pdf","eps"),
                           save_title=NULL,height=13,width=13,...)
```
* `periods` refers the maximum 'length' of the IRF, i.e., how many time periods post-shock you're interested in. For example, if your data are quarterly, then setting `periods = 10` would mean you're interested in the effect of a one standard deviation 'shock' up to 10 quarters after the event. This is what the 'horizon' label on the plotting axis refers to: the number of periods after the 'shock'.
* `cumulative` is a `TRUE` or `FALSE` indicator that will switch between calculating cumulative IRFs (summing the impact of a shock up to a point) or calculating the effect of a shock at a particular point in time (the default).
* `cumul_inds` allows you to choose which IRFs should be cumulative (useful when mixing data that are in levels and differences)
* `var_names` is a character vector of names for your variables
* `percentiles` refers to the percentiles of the IRF distribution (what determines the central red line and the error bands in the plot)
* `which_shock` and `which_response` allow you to select a subset of the IRFs when plotting (useful when working with big VAR systems)
* `shocks_row_order` switches the order of plotting (shocks by row order or column order)
* and the `save`-related variables are there for customizing the save format (pdf or eps, dimensions, etc.).

Example:
```R
data(BMRVARData)
bvar_data <- data.matrix(USMacroData[,2:4])

#

bvar_obj <- new(bvarm)

coef_prior <- c(0.9,0.9,0.9)
p <- 4

bvar_obj$build(bvar_data,TRUE,4) # p =4
bvar_obj$prior(coef_prior,1,1,0.5,0.5,100.0,1.0)
bvar_obj$gibbs(10000)

horizon <- 20
IRF(bvar_obj,horizon,var_names=colnames(USMacroData),save=FALSE)
```
This will plot the IRFs up to 20 periods out; using non-cumulative IRFs; using the variable names from `USMacroData`; and not saving the image.

There are some other features, too. For example, you can impose long-run restrictions by setting:
```R
bvar_obj$irfs_lr_restrict = TRUE
```
and then calling the IRF function.

**Comment by khmahmood** [comment]
I really appreciate your generosity. Thank you so much.
