### ISSUE TITLE
Minnesota prior

### ISSUE THREAD

**Issue by khmahmood** [kthohr/BMR#28]
Hi and sorry to bother you again, is it possible to say that Minnesota prior is a special case from Normal-Inverse Wishart distribution as we are in the Minnesota prior just taking care of the parameters of the mean and the covariance matrix of the parameters of the VAR model?

Thanks in advance.

**Comment by kthohr** [comment]
It's a special case of the conditional Normal-inverse-Wishart prior. The covariance matrix of the disturbance terms, a diagonal matrix estimated using equation-by-equation AR models, is held fixed when drawing the VAR coefficients.

For future reference, the Issues section is to be used solely for questions regarding the use of my package (bugs, etc.), not for general questions about BVAR or DSGE models. Refer to a standard textbook for the theory (e.g., Fabio Canova's monograph).
