### ISSUE TITLE
How to get the confidence interval series from the forecast object

### ISSUE THREAD

**Issue by as4456** [kthohr/BMR#30]
Hi..Could you tell me how to get the confidence interval series from the forecast object for the BVARM model. The forecast object has the following arrays: MeanForecast, PointForecast and Forecasts. Could you tell me what does this last array represent?

**Comment by kthohr** [comment]
The function
```R
forecast(bvar_obj,...)
```
returns two objects: the mean forecast (`forecast_mean`) and a three-dimensional array (`plot_vals`), the latter of which is arranged as: (horizon) x 4 x (number of variables in the model). The 'columns' of `plot_vals` are as follows: [lower confidence interval, point forecast (mean or user-defined percentile), upper confidence interval, forecast horizon index].

**Comment by as4456** [comment]
Ok, so for e.g if I have 6 variables and 7 horizons, the forecast_obj$Forecasts consists of
twenty four 7*6 arrays. Now how to identify the lower confidence interval, higher confidence interval and point forecasts from this.

**Comment by kthohr** [comment]
You are referring to an **old** version of the library. `forecast_obj$Forecasts` are the raw draw-by-draw forecasts. If you wish to continue using the legacy version of BMR, consult the old source code.

**Comment by as4456** [comment]
Hi..Just installed the new version. Could you tell me how to get the Beta which was available in the previous BVARM object. Also is there a way to get fitted values also.

**Comment by kthohr** [comment]
Read the help page:

https://www.kthohr.com/bmr_docs_vars_bvarm.html#definition

The 'fitted values' will change draw-by-draw; they are not stored but can be constructed using `bvarm_model$beta_draws`.

**Comment by as4456** [comment]
ok..but could you tell if the beta generated by the new object when transformed:
matrix(bvar_obj$alpha_pt_mean,nrow=(mp+1),byrow=TRUE),
would be equivalent to the Beta matrix generated by the old BVARM fn

**Comment by kthohr** [comment]
The translation would be
``` R
alpha_pt_mean = c(Beta)
Beta = matrix(c(alpha_pt_mean),ncol=M)
```
As mentioned in the help, `alpha` is the vectorized version of `beta`.
