### ISSUE TITLE
c++lang does not support flag -fopenmp on Mac

### ISSUE THREAD

**Issue by khansamad47** [kthohr/BMR#31]
clang++  -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -std=gnu++11 -fopenmp -DARMA_USE_OPENMP -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c bmlib/src/optim/line_search/more_thuente.cpp -o bmlib/src/optim/line_search/more_thuente.o
clang: error: unsupported option '-fopenmp'
make: *** [bmlib/src/optim/line_search/more_thuente.o] Error 1
ERROR: compilation failed for package ‘BMR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/BMR’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/d2/p7vtwj996tqcyq5z_28jxyfc0000gn/T//RtmpAXPEAw/file682594b6038/BMR_0.11.0.tar.gz’ had non-zero exit status
>

**Comment by kthohr** [comment]
Don't use Apple's distribution of LLVM to compile a package from source -- it doesn't support OpenMP. This is already documented:

https://cran.r-project.org/bin/macosx/tools/

Obtain gfortran6 and clang6, and ensure that the`~/.R/Makevars` file on your system is correct.
