### ISSUE TITLE
IRF - Unit Shocks & Sign Restrictions

### ISSUE THREAD

**Issue by galenwray** [kthohr/BMR#32]
Is there a way to specify unit shocks for the impulse response function? Moreover, is there a way to identify via sign restrictions?

Thanks!

**Comment by kthohr** [comment]
Sign restrictions are not implemented in the package. All IRFs are based on a Cholesky decomposition of the raw covariance matrix of the disturbance terms. You could write or modify existing code to rescale the shocks based on the raw draws, depending on the particular model you're interested in, or even rescale your data, but this is not available out-of-the-box.

**Comment by galenwray** [comment]
Thank you very much for your quick response! Where in the existing code would I be able to rescale the shocks based on the raw draws?

**Comment by kthohr** [comment]
So each (B)VAR model has an `$irf(n_irf_periods)` method that is called by the main `IRF(var_mode,...)` function. It computes the IRFs on a draw-by-draw basis. For example, in the case of the conditional Normal-inverse-Wishart model, the code is located here:

https://github.com/kthohr/BMR/blob/f743d7a592722c8711eb85e70de713058b47490e/src/bmlib/src/var/bvarcnw.cpp#L303-L363

For each draw you would need to rescale the `Sigma` matrix to have unit variances.
