### ISSUE TITLE
forecast(..., plot=FALSE) doesn't work

### ISSUE THREAD

**Issue by CylonScion** [kthohr/BMR#33]
Setting the plot option to FALSE in the forecast() function doesn't suppress the plot generation. In the BVARM [example](https://www.kthohr.com/bmr_docs_vars_bvarm.html), the following still creates plots: 
 
`forecasts <- forecast(bvar_obj,shocks=FALSE,var_names=colnames(USMacroData),back_data=10,save=FALSE, plot=FALSE)`

**Comment by kthohr** [comment]
The documentation for `forecast` is a little dated. The `plot=` option is no longer present in the function.

**Comment by kthohr** [comment]
Should be fixed now.

**Comment by CylonScion** [comment]
Sure does now. Thanks!
