### ISSUE TITLE
Package has a non-empty 'configure.win' file

### ISSUE THREAD

**Issue by andrecvalerio** [kthohr/BMR#34]
Hi!

I'm having a little trouble trying to install the package. I get the following error:

* installing *source* package 'BMR' ...
** libs
Error: (converted from warning) this package has a non-empty 'configure.win' file,
so building only the main architecture
* removing 'C:/Users/B34832/Documents/R/win-library/3.5/BMR'
* restoring previous 'C:/Users/B34832/Documents/R/win-library/3.5/BMR'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/B34832/AppData/Local/Temp/RtmpA7URec/file208416f9453/BMR_0.11.0.tar.gz’ had non-zero exit status

I have Rtools version 3.5.0.4 installed and it seems to be working fine. Also, I'm using Windows 10 and R 3.5. What would you recommend me to do? 

Thank you in advance!

**Comment by tjkvirt** [comment]
Had the same problem. Using install_github("kthohr/BMR", INSTALL_opts="--no-multiarch") worked for me.

**Comment by andrecvalerio** [comment]
It worked! Thanks a lot!

**Comment by mandarpriya** [comment]
Hi 
install_github("kthohr/BMR", INSTALL_opts="--no-multiarch") it seems to work but then what it means no multiarch, so kindly explain this why this issue. I had similar issue for termstrc, and quantstrat packages and yes like using force=TRUE solved my problem but not for BMR. So like can someone enlighten me

**Comment by RGMCASUS** [comment]
To my knowledge, INSTALL_opts="--no-multiarch" implies that either the 64b or the 32b version will be installed, but not both
