### ISSUE TITLE
How to get the posterior draws from the bvar_obj object

### ISSUE THREAD

**Issue by Cribern** [kthohr/BMR#35]
Hello,

I am trying to get the draws of factors that form the distribution, using which I plan to take mean/median later on. I tried running: "bvar_obj$beta_draws". But, I am not able to print/export the full data/matrix.

Is this 'beta_draws' the correct place where draws are stored? And is there any way I can export the matrix/table without printing? Because the matrix will be huge.

Request you to please help.

Thanks in advance!

**Comment by kvasilopoulos** [comment]
When you are asking a question is always advisable to be through a reproducible example. To answer your question, yes draws are stored at `bvar_obj$beta_draws`. Take a look at an example below:

``` r
library(BMR)
#> Loading required package: Rcpp
#> Loading required package: ggplot2
data(BMRVARData)
bvar_data <- data.matrix(USMacroData[,2:4])
coef_prior <- c(0.9,0.9,0.9)
bvar_obj <- new(bvarm)
bvar_obj$build(bvar_data,TRUE,4)
bvar_obj$prior(coef_prior,1,1,0.5,0.5,100.0,1.0)
bvar_obj$gibbs(10000)

draws <- bvar_obj$beta_draws
dim(draws)
#> [1]    13     3 10000

# 13 = 4 lags * 3 vars + constat
# 3 = 3 vars
# 10000 draws

 # Take the constant from the first equation
length(draws[1,1,])
#> [1] 10000
```
