### ISSUE TITLE
Trouble installing BMR in R 3.5.3 version

### ISSUE THREAD

**Issue by pstef2** [kthohr/BMR#38]
Hi!
I had to reinstall R and all packages. I've tried to install BMR as instructed, but I keep getting error messages (I've installed the package in other R versions before without any problems. I'm using Windows). I've tried a few suggestions from here, but nothing worked:

Downloading GitHub repo kthohr/BMR@master
  
   checking for file 'C:\Users\Patricia\AppData\Local\Temp\RtmpmIAjei\remotes342853457398\kthohr-BMR-63565cd/DESCRIPTION' ...
     checking for file 'C:\Users\Patricia\AppData\Local\Temp\RtmpmIAjei\remotes342853457398\kthohr-BMR-63565cd/DESCRIPTION' ...   
√  checking for file 'C:\Users\Patricia\AppData\Local\Temp\RtmpmIAjei\remotes342853457398\kthohr-BMR-63565cd/DESCRIPTION'
-  preparing 'BMR': (1.1s)
   checking DESCRIPTION meta-information ...  
√  checking DESCRIPTION meta-information
-  cleaning src  
-  checking for LF line-endings in source and make files and shell scripts  
-  checking for empty or unneeded directories (940ms)  
-  looking to see if a 'data/datalist' file should be added
-  building 'BMR_0.11.0.tar.gz'
Installing package into ‘C:/Users/Patricia/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'BMR' ...
** libs
Error: this package has a non-empty 'configure.win' file,
so building only the main architecture
* removing 'C:/Users/Patricia/Documents/R/win-library/3.5/BMR'
In R CMD INSTALL
Error in i.p(...) : 
     installation of package ‘C:/Users/Patricia/AppData/Local/Temp/RtmpmIAjei/file34286033278f/BMR_0.11.0.tar.gz’ had non-zero exit status
Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

I've tried a few sugestions from closed issues like install_github("kthohr/BMR", INSTALL_opts="--no-multiarch") and also install_github("kthohr/BMR",force=TRUE)

Thanks in advance

**Comment by kvasilopoulos** [comment]
I've raised this issue in #36 . Can you try the solution provided there?

**Comment by pstef2** [comment]
Thanks for answering. I saw your post and I did try it. It solves "half" of it for me. It installs the package, but not completly (I few functions are missing, such as BVARS, BVARM, etc, but other are not, such as prior, IRF). Here is the warnings I get:
> Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
> > install_github("kthohr/BMR")
Downloading GitHub repo kthohr/BMR@master
     checking for file 'C:\Users\Patricia\AppData\Local\Temp\RtmpmIAjei\remotes34286cb03090\kthohr-BMR-63565cd/DESCRIPTION' ...
     checking for file 'C:\Users\Patricia\AppData\Local\Temp\RtmpmIAjei\remotes34286cb03090\kthohr-BMR-63565cd/DESCRIPTION' ...   
√  checking for file 'C:\Users\Patricia\AppData\Local\Temp\RtmpmIAjei\remotes34286cb03090\kthohr-BMR-63565cd/DESCRIPTION'  
-  preparing 'BMR': (1.1s)  
   checking DESCRIPTION meta-information ...
     checking DESCRIPTION meta-information ...   
√  checking DESCRIPTION meta-information
-  cleaning src  
-  checking for LF line-endings in source and make files and shell scripts (365ms)  
-  checking for empty or unneeded directories (750ms)  
-  looking to see if a 'data/datalist' file should be added
-  building 'BMR_0.11.0.tar.gz'
Installing package into ‘C:/Users/Patricia/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'BMR' ...
** libs
Warning: this package has a non-empty 'configure.win' file,
so building only the main architecture
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c bmlib/src/optim/line_search/more_thuente.cpp -o bmlib/src/optim/line_search/more_thuente.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c bmlib/src/optim/unconstrained/bfgs.cpp -o bmlib/src/optim/unconstrained/bfgs.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c bmlib/src/optim/unconstrained/de.cpp -o bmlib/src/optim/unconstrained/de.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c bmlib/src/mcmc/de.cpp -o bmlib/src/mcmc/de.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c bmlib/src/var/bvarcnw.cpp -o bmlib/src/var/bvarcnw.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c bmlib/src/var/bvarinw.cpp -o bmlib/src/var/bvarinw.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c bmlib/src/var/bvarm.cpp -o bmlib/src/var/bvarm.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c bmlib/src/var/bvars.cpp -o bmlib/src/var/bvars.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c bmlib/src/var/bvartvp.cpp -o bmlib/src/var/bvartvp.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c bmlib/src/var/cvar.cpp -o bmlib/src/var/cvar.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c bmlib/src/filter/chandrasekhar.cpp -o bmlib/src/filter/chandrasekhar.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c bmlib/src/filter/kalman.cpp -o bmlib/src/filter/kalman.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c bmlib/src/lres/gensys_solver.cpp -o bmlib/src/lres/gensys_solver.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c bmlib/src/lres/uhlig_solver.cpp -o bmlib/src/lres/uhlig_solver.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c modules/bvarm_R.cpp -o modules/bvarm_R.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c modules/bvars_R.cpp -o modules/bvars_R.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c modules/bvarcnw_R.cpp -o modules/bvarcnw_R.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c modules/bvarinw_R.cpp -o modules/bvarinw_R.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c modules/bvartvp_R.cpp -o modules/bvartvp_R.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c modules/cvar_R.cpp -o modules/cvar_R.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c modules/gensys_R.cpp -o modules/gensys_R.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c modules/uhlig_R.cpp -o modules/uhlig_R.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c modules/dsge_gensys_R.cpp -o modules/dsge_gensys_R.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c modules/dsge_uhlig_R.cpp -o modules/dsge_uhlig_R.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c modules/dsgevar_gensys_R.cpp -o modules/dsgevar_gensys_R.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.3/include" -DNDEBUG -std=gnu++11 -fopenmp -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"C:/Program Files/R/R-3.5.3/library/Rcpp/include" -I"C:/Users/Patricia/Documents/R/win-library/3.5/RcppArmadillo/include"        -O2 -Wall  -mtune=generic -c modules/dsgevar_uhlig_R.cpp -o modules/dsgevar_uhlig_R.o
C:/Rtools/mingw_32/bin/g++  -shared -s -static-libstdc++ -static-libgcc -fopenmp -o BMR.dll ./bmlib/src/optim/line_search/more_thuente.o ./bmlib/src/optim/unconstrained/bfgs.o ./bmlib/src/optim/unconstrained/de.o ./bmlib/src/mcmc/de.o ./bmlib/src/var/bvarcnw.o ./bmlib/src/var/bvarinw.o ./bmlib/src/var/bvarm.o ./bmlib/src/var/bvars.o ./bmlib/src/var/bvartvp.o ./bmlib/src/var/cvar.o ./bmlib/src/filter/chandrasekhar.o ./bmlib/src/filter/kalman.o ./bmlib/src/lres/gensys_solver.o ./bmlib/src/lres/uhlig_solver.o ./modules/bvarm_R.o ./modules/bvars_R.o ./modules/bvarcnw_R.o ./modules/bvarinw_R.o ./modules/bvartvp_R.o ./modules/cvar_R.o ./modules/gensys_R.o ./modules/uhlig_R.o ./modules/dsge_gensys_R.o ./modules/dsge_uhlig_R.o ./modules/dsgevar_gensys_R.o ./modules/dsgevar_uhlig_R.o -shared -L"C:/PROGRA~1/R/R-35~1.3/bin/i386" -lRlapack -L"C:/PROGRA~1/R/R-35~1.3/bin/i386" -lRblas -lgfortran -lm -lquadmath   -L"C:/PROGRA~1/R/R-35~1.3/bin/i386" -lR 
installing to C:/Users/Patricia/Documents/R/win-library/3.5/BMR/libs/i386
** R
** data
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'BMR'
    finding HTML links ... done
    BMR-package                             html  
    BMRLSData                               html  
    BMRMCData                               html  
    BMRVARData                              html  
    IRF                                     html  
    bvarm                                   html  
    bvars                                   html  
    bvartvp                                 html  
    bvarw                                   html  
    cvar                                    html  
    dsge                                    html  
    finding level-2 HTML links ... done

Rd warning: C:/Users/Patricia/AppData/Local/Temp/RtmpUTtc5F/R.INSTALLb409935e40/BMR/man/dsge.Rd:26: missing link 'forecast.dsge'
Rd warning: C:/Users/Patricia/AppData/Local/Temp/RtmpUTtc5F/R.INSTALLb409935e40/BMR/man/dsge.Rd:26: missing link 'IRF.dsge'
Rd warning: C:/Users/Patricia/AppData/Local/Temp/RtmpUTtc5F/R.INSTALLb409935e40/BMR/man/dsge.Rd:26: missing link 'plot.dsge'
Rd warning: C:/Users/Patricia/AppData/Local/Temp/RtmpUTtc5F/R.INSTALLb409935e40/BMR/man/dsge.Rd:26: missing link 'states.dsge'
    dsgevar                                 html  
Rd warning: C:/Users/Patricia/AppData/Local/Temp/RtmpUTtc5F/R.INSTALLb409935e40/BMR/man/dsgevar.Rd:26: missing link 'forecast.dsgevar'
Rd warning: C:/Users/Patricia/AppData/Local/Temp/RtmpUTtc5F/R.INSTALLb409935e40/BMR/man/dsgevar.Rd:26: missing link 'IRF.dsgevar'
Rd warning: C:/Users/Patricia/AppData/Local/Temp/RtmpUTtc5F/R.INSTALLb409935e40/BMR/man/dsgevar.Rd:26: missing link 'plot.dsgevar'
Rd warning: C:/Users/Patricia/AppData/Local/Temp/RtmpUTtc5F/R.INSTALLb409935e40/BMR/man/dsgevar.Rd:26: missing link 'states.dsgevar'
    forecast                                html  
    gensys                                  html  
Rd warning: C:/Users/Patricia/AppData/Local/Temp/RtmpUTtc5F/R.INSTALLb409935e40/BMR/man/gensys.Rd:57: missing link 'DSGESim'
    gtsplot                                 html  
    mode_check                              html  
    plot                                    html  
    prior                                   html  
    states                                  html  
    uhlig                                   html  
Rd warning: C:/Users/Patricia/AppData/Local/Temp/RtmpUTtc5F/R.INSTALLb409935e40/BMR/man/uhlig.Rd:57: missing link 'DSGESim'
** building package indices
** testing if installed package can be loaded
* DONE (BMR)
In R CMD INSTALL
Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

Thanks

**Comment by kthohr** [comment]
The functions `BVARS` and `BVARM` are from a previous iteration of the package. Check [here](https://www.kthohr.com/bmr_docs_vars_bvarm.html#examples) for an example with the new syntax.

**Comment by pstef2** [comment]
I see.
Thanks for getting back to me
Cheers

Em sex, 22 de mar de 2019 às 09:21, kthohr <notifications@github.com>
escreveu:

**Comment by masoumehsolgi** [comment]
hi,
i use R version  4.0.2 ,i tried to install the package ,i get this error 
Warning in install.packages :
  package ‘BMR’ is not available (for R version 4.0.2)
i tried this too  
remotes::install_version('BMR', version = '0.5.1')
but there was an error
Error in package_find_repo(package, repos) : couldn't find package 'BMR'
could you please help me ?
thanks so much
