### ISSUE TITLE
Error: package or namespace load failed for ‘BMR’ in library.dynam(lib, package, package.lib):

### ISSUE THREAD

**Issue by nihedberg** [kthohr/BMR#39]
Hi, I have problems installing BMR. Mac 10.14.4 Mojave

R version: 3.5.3

I get this error message:

-F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
/bin/sh: -fopenmp: command not found
make: [libBMR] Error 127 (ignored)
** R
** data
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for "BMR" in library.dynam (lib, package, package.lib):
 shared object ‘BMR.so’ not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing "/Library/Frameworks/R.framework/Versions/3.5/Resources/library/BMR"
Error in i.p (...):
  (converted from warning) installation of package "/var/folders/d6/16y4ytbn1lx2wpxzwchg5thh0000gn/T//RtmprsHkwe/file4fe165f53a08/BMR_0.11.0.tar.gz" had non-zero exit status

Everything seems to work up to this point.

I use install_github("kthohr/BMR", force = TRUE)

Sorry, I'm really new to this.

**Comment by kthohr** [comment]
Wrong compiler; Apple's version of LLVM doesn't support OpenMP.
