### ISSUE TITLE
I can't install BMR

### ISSUE THREAD

**Issue by ronanalexand** [kthohr/BMR#41]
> install_github("kthohr/BMR")
Downloading GitHub repo kthohr/BMR@master
✔  checking for file ‘/private/var/folders/ml/hg1rbdqd39b2vhlzm0pn91yw0000gn/T/RtmpEjvhbA/remotes2c4e748d0efd/kthohr-BMR-63565cd/DESCRIPTION’ ...
─  preparing ‘BMR’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘BMR_0.11.0.tar.gz’
   
Installing package into ‘/Users/ronanalexand/Library/R/3.5/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘BMR’ ...
** libs
clang++  -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -std=gnu++11 -fopenmp -DARMA_USE_OPENMP -DUSE_RCPP_ARMADILLO -DARMA_NO_DEBUG -DSTATS_GO_INLINE -I./modules -I./bmlib/include -I./bmlib/include/mcmc -I./bmlib/include/optim -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Users/ronanalexand/Library/R/3.5/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c bmlib/src/optim/line_search/more_thuente.cpp -o bmlib/src/optim/line_search/more_thuente.o
clang: error: unsupported option '-fopenmp'
make: *** [bmlib/src/optim/line_search/more_thuente.o] Error 1
ERROR: compilation failed for package ‘BMR’
* removing ‘/Users/ronanalexand/Library/R/3.5/library/BMR’
Error in i.p(...) : 
  (convertido do aviso) installation of package ‘/var/folders/ml/hg1rbdqd39b2vhlzm0pn91yw0000gn/T//RtmpEjvhbA/file2c4e8fbac2/BMR_0.11.0.tar.gz’ had non-zero exit status

**Comment by ronanalexand** [comment]
I am using a mac

**Comment by kthohr** [comment]
Use an OpenMP-compatible compiler, not Apple's version of Clang. This has been addressed in other issues.

**Comment by ronanalexand** [comment]
Thanks for the quick reply
