### ISSUE TITLE
Giving different percentiles in the forecast function

### ISSUE THREAD

**Issue by vikaskumar30** [kthohr/BMR#44]
Hi,
How do I get the percentiles c(0.05,0.32,0.5,0.68,0.95) in the forecast function, i.e 4 confidence bands along with the median here.

Apparently it just gives me 4 columns with the last column being the index number.
 I believe it just computes the 5th, Mean and 95th percentile.

Is there a way to get all the bands at once.

Thanks

**Comment by kthohr** [comment]
You can only set 3 percentiles using the `forecast` function. To extract the full forecast distribution, use the `forecast` method on the object. For example: `my_bvar_obj$forecast(periods, incl_shocks)$forecast_vals` -- this will return a cube with dimensions (forecast horizon) x (number of series) x (number of draws).
