### ISSUE TITLE
unable to install: "undefined symbol: zgesdd_"

### ISSUE THREAD

**Issue by vapniks** [kthohr/BMR#6]
I'm using: R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet" on Ubuntu 14.04 
I have installed the latest versions of  Rcpp, RcppArmadillo, ggplot2, and doSNOW
I use the following commands to do the install:
```
 > library(devtools)
 > install_github("BMR","kthohr")
```
and I get the following error:
```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/vapniks/R/x86_64-pc-linux-gnu-library/current_libs/BMR/libs/BMR.so':
  /home/vapniks/R/x86_64-pc-linux-gnu-library/current_libs/BMR/libs/BMR.so: undefined symbol: zgesdd_
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/vapniks/R/x86_64-pc-linux-gnu-library/current_libs/BMR’
Error: Command failed (1)
In addition: Warning message:
Username parameter is deprecated. Please use kthohr/BMR 
```
Help!

**Comment by kthohr** [comment]
Did you include a Makevars file in BMR/src to link your Lapack/BLAS libraries? (Not every OS requires this, but I believe most Linux distros need this.)

**Comment by vapniks** [comment]
No, it doesn't say anything about this on the website. Will try doing it manually.

**Comment by vapniks** [comment]
OK, adding a Makevars file in the src directory with the following content fixed the problem for me:
```
PKG_LIBS = $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)
```

**Comment by kthohr** [comment]
Good to hear.
