### ISSUE TITLE
Unable to compile package for R 3.2

### ISSUE THREAD

**Issue by arvind-ilamaran** [kthohr/BMR#7]

**Comment by kthohr** [comment]
I need more details than this. Your OS, what error came up, etc.

**Comment by arvind-ilamaran** [comment]
Ubuntu Precise. and I tried installing from the source. I am pasting the output below:

install.packages("~/Desktop//BMR-master.zip",repos=NULL)
Installing package into ‘/home/t330/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
Error in rawToChar(block[seq_len(ns)]) : 
  embedded nul in string: 'PK\003\004\n\0\0\0\0\0\xd4CKF\0\0\0\0\0\0\0\0\0\0\0\0\v\0\t\0BMR-master/UT\005\0\001\xb1\x83\xdbTPK\003\004\n\0\0\0\b\0\xd4CKFA\x80dx\xfc\0\0\0\x8a\001\0\0\026\0\t\0BMR-master/DESCRIPTI'
Warning in install.packages :
  installation of package ‘/home/t330/Desktop//BMR-master.zip’ had non-zero exit status
>

**Comment by kthohr** [comment]
You need to compile the package from terminal, not in R; it's not a binary file.

For Linux, you'll need to add a Makevars file to the src folder to indicate where your Lapack and BLAS libraries are located; see the previous closed issues for an example of this.
