### ISSUE TITLE
Can not install under in Ubuntu-15.04/R-3.2.0/Rstudio-0.98

### ISSUE THREAD

**Issue by nianjin06** [kthohr/BMR#8]
Dear Hohr,      I install BMR by the following commands,  and 'Lapack-3.5.0' has been compiled,

                 '>library(devtools)
                 >install_github("kthohr/BMR")
installing to /usr/local/lib/R/site-library/BMR/libs
** R
** data
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/site-library/BMR/libs/BMR.so':
  /usr/local/lib/R/site-library/BMR/libs/BMR.so: undefined symbol: zgesdd_
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/BMR’
* restoring previous ‘/usr/local/lib/R/site-library/BMR’
Error: Command failed (1)'

I have already read the closed previous issues, and know need to add a new file Makevar in BMR/src with the content " PKG_LIBS = `$(R_HOME)/bin/Rscript -e "Rcpp:::LdFlags()"` $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)". 

But I do not know how to finish it.  
I download from the github,  and add the Makevar file to BMR/src,  and tar the files as BMR.tar.gz.
and  use R CMD INSTALL BMR.tar.gz to install. However, it does not work.

How should I do to accomplish it, and could you give a cookbook method. Thanks

**Comment by kthohr** [comment]
Hmm. Try the following steps, which seemed to work for another Ubuntu user (and for me).

"You should download the BMR source code from my GitHub page:

https://github.com/kthohr/BMR

A direct link to a zip file is here:

https://github.com/kthohr/BMR/archive/master.zip

After you unzip the files, place a Makevars file in the BMR/src folder. You can use the one here:

http://bayes.squarespace.com/storage/bmr/Makevars

Make sure you have installed the packages listed on my site:

install.packages("RcppArmadillo")
install.packages("ggplot2")
install.packages("doSNOW")

and that you installed the 'r-base-dev' version of R.

It should then be as simple as typing

sudo R CMD INSTALL ~/Desktop/BMR

in the terminal, where you change '~/Desktop/BMR' to wherever you placed the unzipped files."

Let me know if that works.

**Comment by nianjin06** [comment]
Thanks for your great great great help,  It really works.

**Comment by kthohr** [comment]
Good to hear!
